"""Built-in C1+ English word lists: AWL, phrasal verbs, idioms."""
from typing import List, Tuple

# Each entry: (word_or_phrase, brief_hint)
# Claude generates full card content; hints help with disambiguation

# ── Academic Word List (Coxhead AWL sublists 1-10, headwords) ─────
# Source: Averil Coxhead's AWL — most frequent academic English words
AWL: List[Tuple[str, str]] = [
    # Sublist 1 (most frequent)
    ("analyse", "examine in detail"),
    ("approach", "way of dealing with something"),
    ("area", "region or field"),
    ("assess", "evaluate or estimate"),
    ("assume", "suppose without proof"),
    ("authority", "power or expert body"),
    ("available", "obtainable or accessible"),
    ("benefit", "advantage or gain"),
    ("concept", "abstract idea"),
    ("consist", "be composed of"),
    ("constitute", "make up or form"),
    ("context", "circumstances or setting"),
    ("contract", "formal agreement"),
    ("create", "bring into existence"),
    ("data", "facts and statistics"),
    ("define", "state meaning precisely"),
    ("derive", "obtain from a source"),
    ("distribute", "spread or hand out"),
    ("economy", "system of trade/finance"),
    ("environment", "surroundings or conditions"),
    ("establish", "set up or prove"),
    ("estimate", "approximate calculation"),
    ("evident", "clearly seen or understood"),
    ("export", "send goods abroad"),
    ("factor", "contributing element"),
    ("finance", "management of money"),
    ("formula", "rule or method"),
    ("function", "purpose or role"),
    ("identify", "recognize or establish"),
    ("income", "money received"),
    ("indicate", "point out or show"),
    ("individual", "single person"),
    ("interpret", "explain the meaning of"),
    ("involve", "include as a part"),
    ("issue", "important topic or problem"),
    ("labour", "work or workforce"),
    ("legal", "relating to law"),
    ("legislate", "make laws"),
    ("major", "important or significant"),
    ("method", "systematic procedure"),
    ("occur", "happen or take place"),
    ("percent", "per hundred"),
    ("period", "length of time"),
    ("policy", "course of action"),
    ("principle", "fundamental truth"),
    ("proceed", "go forward or continue"),
    ("process", "series of actions"),
    ("require", "need or demand"),
    ("research", "systematic investigation"),
    ("respond", "reply or react"),
    ("role", "function or part played"),
    ("section", "distinct part"),
    ("sector", "area or division"),
    ("significant", "important or notable"),
    ("similar", "resembling something"),
    ("source", "origin or reference"),
    ("specific", "particular or exact"),
    ("structure", "arrangement or organization"),
    ("theory", "system of ideas"),
    ("vary", "differ or change"),
    # Sublist 2
    ("achieve", "accomplish successfully"),
    ("acquire", "gain or obtain"),
    ("administer", "manage or organize"),
    ("affect", "have an effect on"),
    ("appropriate", "suitable or proper"),
    ("aspect", "particular feature"),
    ("assist", "help or aid"),
    ("category", "class or group"),
    ("chapter", "main division"),
    ("commission", "formal group or task"),
    ("community", "group sharing common traits"),
    ("complex", "consisting of many parts"),
    ("compute", "calculate"),
    ("conclude", "bring to an end; deduce"),
    ("conduct", "carry out or manage"),
    ("consequence", "result or effect"),
    ("construct", "build or form"),
    ("consume", "use up or eat"),
    ("credit", "acknowledgment; financial trust"),
    ("culture", "customs and achievements"),
    ("design", "plan or create"),
    ("distinct", "clearly different"),
    ("element", "component or part"),
    ("equate", "consider equal"),
    ("evaluate", "judge or assess"),
    ("feature", "distinctive attribute"),
    ("final", "last or ultimate"),
    ("focus", "center of attention"),
    ("impact", "strong effect"),
    ("injure", "harm or damage"),
    ("institute", "organization; establish"),
    ("invest", "put money into"),
    ("item", "individual article"),
    ("journal", "periodical publication"),
    ("maintain", "keep in condition"),
    ("normal", "usual or standard"),
    ("obtain", "get or acquire"),
    ("participate", "take part in"),
    ("perceive", "become aware of"),
    ("positive", "constructive or affirmative"),
    ("potential", "possible but not yet actual"),
    ("previous", "existing before"),
    ("primary", "first in importance"),
    ("purchase", "buy"),
    ("range", "extent or variety"),
    ("region", "area or district"),
    ("regulate", "control by rules"),
    ("relevant", "closely connected"),
    ("reside", "live in a place"),
    ("resource", "supply or asset"),
    ("restrict", "limit or control"),
    ("secure", "safe; obtain"),
    ("seek", "try to find or obtain"),
    ("select", "carefully choose"),
    ("site", "location or place"),
    ("strategy", "plan to achieve a goal"),
    ("survey", "general examination"),
    ("text", "written work"),
    ("tradition", "custom passed down"),
    ("transfer", "move from one place to another"),
    # Sublist 3
    ("alternative", "another possibility"),
    ("circumstance", "condition or situation"),
    ("comment", "remark or observation"),
    ("compensate", "make up for"),
    ("component", "part of a larger whole"),
    ("consent", "permission or agreement"),
    ("considerable", "notably large"),
    ("constant", "unchanging; continuous"),
    ("constrain", "restrict or limit"),
    ("contribute", "give or add to"),
    ("convention", "accepted practice; gathering"),
    ("coordinate", "organize together"),
    ("core", "central or essential part"),
    ("corporate", "relating to a business"),
    ("correspond", "match; communicate by letter"),
    ("criteria", "standards for judging"),
    ("deduce", "reach a conclusion by reasoning"),
    ("demonstrate", "show clearly; prove"),
    ("document", "official paper; record"),
    ("dominate", "have control over"),
    ("emphasis", "special importance"),
    ("ensure", "make certain"),
    ("exclude", "shut out or omit"),
    ("framework", "basic structure"),
    ("fund", "sum of money; provide money"),
    ("illustrate", "explain with examples"),
    ("immigrate", "come to live in a new country"),
    ("imply", "suggest indirectly"),
    ("initial", "first or beginning"),
    ("instance", "example or occurrence"),
    ("interact", "act upon each other"),
    ("justify", "show to be right or reasonable"),
    ("layer", "sheet or level"),
    ("link", "connection"),
    ("locate", "find the position of"),
    ("maximize", "make as large as possible"),
    ("minor", "lesser in importance"),
    ("negate", "deny or make ineffective"),
    ("outcome", "result or consequence"),
    ("partner", "associate or companion"),
    ("philosophy", "study of fundamental nature"),
    ("physical", "relating to the body or material"),
    ("proportion", "comparative part; ratio"),
    ("publish", "make available to public"),
    ("react", "respond to something"),
    ("register", "official list; record"),
    ("rely", "depend on"),
    ("remove", "take away"),
    ("scheme", "plan or arrangement"),
    ("sequence", "order of succession"),
    ("sex", "gender"),
    ("shift", "move or change"),
    ("specify", "state precisely"),
    ("sufficient", "enough"),
    ("task", "piece of work"),
    ("technical", "relating to a technique"),
    ("technique", "method or skill"),
    ("technology", "application of scientific knowledge"),
    ("valid", "sound; legally acceptable"),
    ("volume", "amount; book"),
    # Sublist 4-5 (selected high-value words)
    ("access", "right or ability to use"),
    ("adequate", "sufficient or satisfactory"),
    ("amend", "make changes to"),
    ("annual", "happening every year"),
    ("apparent", "clearly visible; seeming"),
    ("approximate", "close to the actual"),
    ("attribute", "characteristic; ascribe to"),
    ("capacity", "ability to contain; capability"),
    ("civil", "relating to citizens"),
    ("clause", "section of a document"),
    ("coherent", "logical and consistent"),
    ("coincide", "occur at the same time"),
    ("collapse", "fall down; fail suddenly"),
    ("colleague", "fellow worker"),
    ("compile", "collect and assemble"),
    ("comprehensive", "thorough; inclusive"),
    ("confer", "discuss; grant"),
    ("confirm", "establish the truth of"),
    ("contemporary", "modern; of the same time"),
    ("contradict", "deny the truth of"),
    ("controversy", "prolonged public disagreement"),
    ("crucial", "of great importance"),
    ("currency", "money system"),
    ("decade", "period of ten years"),
    ("decline", "decrease; refuse"),
    ("definite", "clearly defined; certain"),
    ("deny", "refuse to admit"),
    ("detect", "discover or identify"),
    ("deviate", "depart from the norm"),
    ("dimension", "measurable extent; aspect"),
    ("discriminate", "distinguish; treat unfairly"),
    ("display", "show or exhibit"),
    ("dispose", "get rid of; arrange"),
    ("domain", "area of activity; territory"),
    ("domestic", "relating to the home or country"),
    ("draft", "preliminary version"),
    ("enable", "make possible"),
    ("enforce", "compel compliance"),
    ("entity", "a thing with distinct existence"),
    ("equivalent", "equal in value"),
    ("erode", "gradually wear away"),
    ("error", "mistake"),
    ("ethnic", "relating to a racial group"),
    ("evolve", "develop gradually"),
    ("exceed", "go beyond a limit"),
    ("expand", "become larger"),
    ("expose", "make visible; subject to risk"),
    ("external", "coming from outside"),
    ("facilitate", "make easier"),
    ("fluctuate", "vary irregularly"),
    ("generate", "produce or create"),
    ("globe", "the world"),
    ("guarantee", "promise or assurance"),
    ("hence", "as a consequence"),
    ("hierarchy", "ranking system"),
    ("hypothesis", "proposed explanation"),
    ("ideology", "set of beliefs"),
    ("ignorance", "lack of knowledge"),
    ("implement", "put into effect"),
    ("implicit", "implied but not stated"),
    ("impose", "force upon"),
    ("incentive", "motivation or encouragement"),
    ("incidence", "occurrence or rate"),
    ("incorporate", "include as part"),
    ("index", "indicator; alphabetical list"),
    ("inhibit", "hinder or restrain"),
    ("inherent", "existing as a natural part"),
    ("innovate", "introduce something new"),
    ("insert", "place inside"),
    ("integrity", "honesty; wholeness"),
    ("intelligence", "ability to learn; information"),
    ("intense", "extreme or forceful"),
    ("intervene", "come between; take action"),
    ("isolate", "set apart"),
    ("liberal", "open-minded; generous"),
    ("licence", "official permission"),
    ("logic", "reasoning; system of principles"),
    ("manipulate", "handle skillfully; influence unfairly"),
    ("mature", "fully developed"),
    ("mediate", "intervene to resolve"),
    ("medium", "means; middle quality"),
    ("mental", "relating to the mind"),
    ("migrate", "move to a new area"),
    ("military", "relating to armed forces"),
    ("minimal", "of a minimum amount"),
    ("ministry", "government department"),
    ("modify", "make partial changes to"),
    ("monitor", "observe and check"),
    ("motive", "reason for doing something"),
    ("mutual", "shared by two or more"),
    ("neutral", "impartial; not taking sides"),
    ("nevertheless", "in spite of that"),
    ("nonetheless", "in spite of that"),
    ("norm", "standard or usual pattern"),
    ("notion", "concept or idea"),
    ("objective", "goal; unbiased"),
    ("occupy", "reside in; fill"),
    ("odd", "strange; not even"),
    ("offset", "counterbalance"),
    ("ongoing", "continuing"),
    ("option", "choice or alternative"),
    ("orient", "align or direct"),
    ("output", "amount produced"),
    ("overall", "in general; total"),
    ("overlap", "extend over and cover partly"),
    ("panel", "flat section; group of experts"),
    ("parallel", "similar; occurring at the same time"),
    ("parameter", "limit or boundary; variable"),
    ("passive", "accepting without resistance"),
    ("phase", "distinct stage"),
    ("phenomenon", "observable event"),
    ("practitioner", "person actively engaged"),
    ("precede", "come before"),
    ("precise", "exact and accurate"),
    ("predict", "forecast"),
    ("predominant", "most common or important"),
    ("presume", "suppose; take for granted"),
    ("principal", "main; head of school"),
    ("prior", "existing before"),
    ("professional", "relating to a profession"),
    ("prohibit", "formally forbid"),
    ("project", "planned undertaking; forecast"),
    ("promote", "support; advance"),
    ("protocol", "official procedure"),
    ("pursue", "follow or chase; continue"),
    ("quote", "repeat words; state a price"),
    ("ratio", "quantitative relation"),
    ("regime", "government; system"),
    ("reinforce", "strengthen"),
    ("reject", "refuse to accept"),
    ("release", "set free; make available"),
    ("reluctance", "unwillingness"),
    ("restrain", "hold back"),
    ("retain", "keep or continue to have"),
    ("reveal", "make known"),
    ("revenue", "income, especially of a state"),
    ("reverse", "move backward; opposite"),
    ("rigid", "stiff; strict"),
    ("route", "way or course"),
    ("scenario", "possible sequence of events"),
    ("scope", "extent or range"),
    ("simulate", "imitate"),
    ("solely", "only; exclusively"),
    ("somewhat", "to some extent"),
    ("submit", "present for consideration; yield"),
    ("subordinate", "lower in rank"),
    ("subsequent", "coming after"),
    ("subsidy", "financial aid"),
    ("substitute", "replacement"),
    ("successor", "person who follows another"),
    ("supplement", "add to; additional material"),
    ("suspend", "temporarily stop; hang"),
    ("sustain", "maintain; support"),
    ("symbol", "thing representing something else"),
    ("target", "object of aim"),
    ("temporary", "lasting for a limited time"),
    ("tense", "strained; verb form"),
    ("terminate", "bring to an end"),
    ("theme", "subject or topic"),
    ("thereby", "by that means"),
    ("thesis", "statement to be proved; dissertation"),
    ("topic", "subject of discussion"),
    ("trace", "find; mark left behind"),
    ("transit", "passage; transport"),
    ("transmit", "send or pass on"),
    ("transport", "carry from one place to another"),
    ("trigger", "cause to happen"),
    ("ultimate", "final; best possible"),
    ("undergo", "experience or be subjected to"),
    ("underlie", "be the basis of"),
    ("undertake", "commit to and begin"),
    ("uniform", "same throughout; outfit"),
    ("unify", "make or become united"),
    ("unique", "being the only one"),
    ("utilise", "make practical use of"),
    ("via", "by way of"),
    ("virtual", "almost; computer-simulated"),
    ("visible", "able to be seen"),
    ("visual", "relating to seeing"),
    ("widespread", "found over a large area"),
]

# ── Phrasal Verbs (C1+ level) ────────────────────────────────────
PHRASAL_VERBS: List[Tuple[str, str]] = [
    ("account for", "explain the reason for"),
    ("back up", "support; make a copy"),
    ("bear in mind", "remember; consider"),
    ("break down", "stop functioning; analyse into parts"),
    ("break through", "make a sudden advance"),
    ("bring about", "cause to happen"),
    ("bring up", "raise a topic; raise a child"),
    ("brush up on", "review and improve"),
    ("build up", "increase gradually"),
    ("call for", "demand; require"),
    ("call off", "cancel"),
    ("carry on", "continue"),
    ("carry out", "perform; execute"),
    ("catch on", "become popular; understand"),
    ("catch up with", "reach the same level as"),
    ("come about", "happen; occur"),
    ("come across", "find by chance; seem"),
    ("come down to", "be essentially about"),
    ("come up with", "think of; produce"),
    ("count on", "rely on"),
    ("cut back on", "reduce"),
    ("cut down on", "reduce consumption of"),
    ("deal with", "handle; address"),
    ("do away with", "abolish; get rid of"),
    ("do without", "manage without"),
    ("draw on", "use as a resource"),
    ("draw up", "prepare a plan or document"),
    ("drop out", "leave; withdraw"),
    ("dwell on", "think or talk about at length"),
    ("embark on", "begin a course of action"),
    ("end up", "eventually reach a state"),
    ("factor in", "include as a relevant element"),
    ("fall behind", "fail to keep up"),
    ("fall through", "fail to happen"),
    ("figure out", "understand; solve"),
    ("fill in", "complete; substitute"),
    ("find out", "discover"),
    ("follow up", "pursue further"),
    ("get across", "communicate effectively"),
    ("get along with", "have a good relationship"),
    ("get around to", "finally do something"),
    ("get away with", "escape punishment"),
    ("get by", "manage to survive"),
    ("get over", "recover from"),
    ("get through", "finish; survive difficulty"),
    ("give in", "yield; surrender"),
    ("give up", "stop trying; abandon"),
    ("go about", "approach or tackle"),
    ("go ahead", "proceed"),
    ("go along with", "agree with; support"),
    ("go over", "review; examine"),
    ("go through", "experience; examine carefully"),
    ("hand in", "submit"),
    ("hand over", "give control of"),
    ("hold back", "restrain; hesitate"),
    ("hold on", "wait; grip tightly"),
    ("hold up", "delay; remain strong"),
    ("iron out", "resolve problems"),
    ("jot down", "write quickly"),
    ("keep up with", "stay at the same level"),
    ("kick off", "begin; start"),
    ("knock out", "defeat; produce quickly"),
    ("lay off", "dismiss from employment"),
    ("lay out", "arrange; explain clearly"),
    ("leave out", "omit"),
    ("let down", "disappoint"),
    ("live up to", "meet expectations"),
    ("look after", "take care of"),
    ("look into", "investigate"),
    ("look up to", "admire; respect"),
    ("make out", "discern; understand"),
    ("make up", "invent; constitute; reconcile"),
    ("make up for", "compensate for"),
    ("map out", "plan in detail"),
    ("narrow down", "reduce the number of options"),
    ("opt for", "choose"),
    ("opt out", "choose not to participate"),
    ("pass on", "transmit; decline"),
    ("pay off", "be successful; finish paying"),
    ("phase out", "gradually discontinue"),
    ("pick up", "learn informally; collect"),
    ("pin down", "define precisely"),
    ("point out", "indicate; draw attention to"),
    ("pull off", "succeed in something difficult"),
    ("put across", "communicate clearly"),
    ("put forward", "propose; suggest"),
    ("put off", "postpone; discourage"),
    ("put up with", "tolerate"),
    ("rely on", "depend on"),
    ("rule out", "exclude"),
    ("run into", "encounter unexpectedly"),
    ("run out of", "exhaust the supply"),
    ("scale up", "increase in size or scope"),
    ("set back", "delay; cost"),
    ("set out", "begin a journey; intend"),
    ("set up", "establish; arrange"),
    ("settle for", "accept something less than ideal"),
    ("show up", "arrive; become visible"),
    ("shut down", "close; stop operating"),
    ("sign off on", "give formal approval"),
    ("sign up", "register; enrol"),
    ("single out", "choose from a group"),
    ("slow down", "reduce speed"),
    ("sort out", "resolve; organize"),
    ("speed up", "increase speed"),
    ("stand for", "represent; tolerate"),
    ("stand out", "be noticeable"),
    ("step down", "resign from a position"),
    ("step up", "increase; take on more"),
    ("stick to", "continue with; adhere"),
    ("sum up", "summarize"),
    ("take into account", "consider"),
    ("take on", "accept; employ; challenge"),
    ("take over", "assume control"),
    ("take up", "begin; occupy space/time"),
    ("talk over", "discuss"),
    ("tear down", "demolish"),
    ("think over", "consider carefully"),
    ("throw out", "discard; reject"),
    ("tie in with", "be connected to"),
    ("touch on", "mention briefly"),
    ("track down", "find after searching"),
    ("trade off", "exchange one thing for another"),
    ("turn down", "reject; reduce"),
    ("turn out", "prove to be; produce"),
    ("turn up", "arrive; increase"),
    ("use up", "consume entirely"),
    ("ward off", "prevent; keep away"),
    ("weigh up", "assess"),
    ("wind up", "end up; finish"),
    ("work out", "solve; exercise; succeed"),
    ("write off", "dismiss; cancel a debt"),
    # ── Extended: Workplace & Professional ──
    ("answer to", "be accountable to a superior"),
    ("branch out", "expand into new areas of activity"),
    ("burn out", "become exhausted from overwork"),
    ("clamp down on", "enforce rules more strictly"),
    ("clock in", "register arrival at work"),
    ("clock out", "register departure from work"),
    ("come into force", "become effective (law/rule)"),
    ("crack down on", "take severe measures against"),
    ("dawn on", "gradually become clear to someone"),
    ("fall back on", "resort to when other options fail"),
    ("fend for oneself", "manage without help"),
    ("free up", "make available (time, resources)"),
    ("gear up for", "prepare for something important"),
    ("knuckle down", "start working hard; apply oneself"),
    ("latch onto", "attach to; seize on an idea"),
    ("mull over", "think carefully about; ponder"),
    ("own up to", "admit responsibility for"),
    ("pan out", "turn out; develop (how did it pan out?)"),
    ("phase in", "introduce gradually"),
    ("press ahead with", "continue determinedly"),
    ("ramp up", "increase sharply"),
    ("rope in", "persuade someone to help"),
    ("slack off", "work less hard; become lazy"),
    ("sound out", "cautiously ask someone's opinion"),
    ("stand in for", "substitute for someone"),
    ("stem from", "originate from; be caused by"),
    ("take to", "begin to like; start doing habitually"),
    ("water down", "make weaker or less effective"),
    ("whittle down", "gradually reduce a list/number"),
    ("zero in on", "focus precisely on"),
    # ── Extended: Emotions & Relationships ──
    ("bottle up", "suppress emotions; not express feelings"),
    ("cheer up", "become or make happier"),
    ("clam up", "suddenly stop talking from nervousness"),
    ("come around", "change one's mind; regain consciousness"),
    ("confide in", "tell secrets/private matters to someone"),
    ("cool off", "calm down after anger"),
    ("fawn over", "show excessive attention/affection"),
    ("flare up", "suddenly become angry; recur (illness)"),
    ("grow on", "gradually become liked by someone"),
    ("lighten up", "become less serious; relax"),
    ("look down on", "regard as inferior"),
    ("look up", "improve (things are looking up)"),
    ("mope around", "be listless and gloomy"),
    ("patch up", "repair a relationship or quarrel"),
    ("pluck up courage", "summon courage"),
    ("snap out of", "force oneself out of a bad mood"),
    ("stick up for", "defend; support someone"),
    ("warm to", "begin to like or feel comfortable with"),
    ("wear off", "gradually disappear (excitement, effect)"),
    ("wind down", "relax after stress; gradually decrease"),
    # ── Extended: Health & Body ──
    ("break out in", "suddenly develop (a rash, sweat)"),
    ("bring around", "revive someone who is unconscious"),
    ("build up immunity", "strengthen immune system gradually"),
    ("come down with", "begin to suffer from an illness"),
    ("come round", "regain consciousness"),
    ("cut out", "stop consuming (cut out sugar)"),
    ("do in", "exhaust completely"),
    ("ease off", "become less severe (pain, pressure)"),
    ("fight off", "resist an illness or infection"),
    ("pass out", "lose consciousness"),
    ("pull through", "survive a serious illness"),
    ("run down", "become weak/exhausted"),
    ("seize up", "become stiff; stop working (muscles)"),
    ("swell up", "become swollen"),
    ("throw up", "vomit"),
    ("top up", "refill (medication, vitamins)"),
    ("wear down", "gradually weaken through persistent pressure"),
    ("work off", "get rid of through activity (stress, calories)"),
    # ── Extended: Parenting & Household ──
    ("clean up after", "tidy the mess someone else made"),
    ("clear out", "remove unwanted items; empty a space"),
    ("clear up", "tidy; resolve confusion; weather improves"),
    ("come along", "make progress"),
    ("doze off", "fall asleep unintentionally"),
    ("drop off", "fall asleep; deliver someone somewhere"),
    ("fix up", "repair; renovate"),
    ("give away", "donate; accidentally reveal"),
    ("grow out of", "become too big/mature for"),
    ("keep to", "follow; adhere to (a schedule)"),
    ("lay down the law", "state rules firmly"),
    ("let off", "not punish; release"),
    ("measure up", "meet the required standard"),
    ("pack away", "put things into storage"),
    ("play up", "cause problems (child, device)"),
    ("put away", "return something to its proper place"),
    ("tidy up", "make neat and organized"),
    ("tire out", "exhaust someone"),
    ("tuck in", "push bedcovers around a child; eat heartily"),
    ("turn around", "reverse a bad situation; rotate"),
    ("watch out for", "be careful about; look after"),
    # ── Extended: Finance ──
    ("bail out", "rescue financially"),
    ("cash in on", "profit from; exploit"),
    ("chip in", "contribute money as a group"),
    ("come to", "amount to (a total)"),
    ("cough up", "reluctantly pay money"),
    ("dip into savings", "use part of saved money"),
    ("fork out", "pay reluctantly, usually a large sum"),
    ("live off", "depend on financially"),
    ("mark down", "reduce the price"),
    ("mark up", "increase the price"),
    ("rip off", "overcharge; swindle"),
    ("save up", "accumulate money over time"),
    ("scrape by", "manage to survive financially with difficulty"),
    ("sell off", "sell remaining stock cheaply"),
    ("set aside", "reserve money or time for a purpose"),
    ("shell out", "pay a large amount reluctantly"),
    ("snap up", "buy quickly before others can"),
    ("splash out on", "spend a lot on a luxury"),
    ("stack up", "compare (how does it stack up?)"),
    ("tide over", "help through a difficult period"),
    ("tighten up", "make stricter (regulations, budget)"),
    # ── Extended: Social & General Advanced ──
    ("bank on", "rely on; count on confidently"),
    ("blend in", "fit in without being noticed"),
    ("boil down to", "be reducible to the essential point"),
    ("brush off", "dismiss; treat as unimportant"),
    ("butt in", "interrupt rudely"),
    ("cave in", "yield under pressure; collapse"),
    ("chip away at", "gradually reduce or undermine"),
    ("close in on", "approach; get nearer to catching"),
    ("come off", "succeed; give an impression"),
    ("crop up", "appear unexpectedly"),
    ("die down", "gradually become less intense"),
    ("drag on", "continue for too long"),
    ("eat away at", "gradually destroy; worry persistently"),
    ("fizzle out", "gradually end weakly"),
    ("flesh out", "add more detail to"),
    ("gloss over", "treat superficially; minimize"),
    ("hammer out", "negotiate with difficulty until agreed"),
    ("home in on", "direct attention precisely at"),
    ("leaf through", "turn pages quickly; browse"),
    ("level with", "speak honestly and directly to"),
    ("live down", "overcome the shame of"),
    ("play down", "minimize the importance of"),
    ("pop up", "appear suddenly or unexpectedly"),
    ("prop up", "support; prevent from failing"),
    ("rally around", "unite in support of someone"),
    ("reel off", "say quickly from memory"),
    ("root for", "support enthusiastically"),
    ("stamp out", "eliminate; eradicate"),
    ("stumble across", "find by chance"),
    ("talk into", "persuade someone to do something"),
    ("talk out of", "dissuade someone from doing something"),
    ("tip off", "give secret information; warn"),
    ("tone down", "make less extreme; moderate"),
    ("usher in", "mark the beginning of (a new era)"),
    ("vouch for", "guarantee; speak in support of"),
    ("weed out", "remove undesirable elements"),
]

# ── Idioms & Fixed Expressions (C1+) ─────────────────────────────
IDIOMS: List[Tuple[str, str]] = [
    ("a blessing in disguise", "something good that initially seemed bad"),
    ("a can of worms", "a complex problematic situation"),
    ("a double-edged sword", "something with both advantages and disadvantages"),
    ("a far cry from", "very different from"),
    ("a rule of thumb", "a practical guideline"),
    ("a shot in the dark", "a wild guess"),
    ("a slippery slope", "a course leading to disaster"),
    ("add insult to injury", "make a bad situation worse"),
    ("at the end of the day", "ultimately; when all is considered"),
    ("back to square one", "back to the beginning"),
    ("ball is in your court", "it's your turn to act"),
    ("barking up the wrong tree", "pursuing a mistaken approach"),
    ("beat around the bush", "avoid the main topic"),
    ("behind the scenes", "out of public view"),
    ("bend over backwards", "try extremely hard to help"),
    ("bite off more than you can chew", "take on too much"),
    ("bite the bullet", "endure something painful with courage"),
    ("break even", "neither profit nor lose"),
    ("break new ground", "do something innovative"),
    ("break the ice", "relieve tension in a social situation"),
    ("bridge the gap", "reduce differences"),
    ("burn bridges", "destroy relationships irreparably"),
    ("burn the midnight oil", "work late into the night"),
    ("by and large", "on the whole; generally"),
    ("call it a day", "stop working"),
    ("call the shots", "make the decisions"),
    ("come to grips with", "deal with; understand"),
    ("cost an arm and a leg", "be very expensive"),
    ("cross that bridge when you come to it", "deal with a problem when it arises"),
    ("cut corners", "do something cheaply or poorly"),
    ("cut to the chase", "get to the point"),
    ("down the line", "in the future"),
    ("draw a line", "set a limit"),
    ("draw the short straw", "be the unlucky one"),
    ("drop the ball", "make a mistake; fail to act"),
    ("easier said than done", "harder than it sounds"),
    ("face the music", "accept consequences"),
    ("few and far between", "rare; scarce"),
    ("food for thought", "something worth thinking about"),
    ("from scratch", "from the very beginning"),
    ("get cold feet", "become nervous; hesitate"),
    ("get off the ground", "begin successfully"),
    ("get out of hand", "become uncontrollable"),
    ("get the ball rolling", "start something"),
    ("get to the bottom of", "find the true cause"),
    ("give the benefit of the doubt", "trust despite uncertainty"),
    ("go back to the drawing board", "start over with a new plan"),
    ("go the extra mile", "make more effort than expected"),
    ("go with the flow", "accept the situation"),
    ("hang in there", "persist; don't give up"),
    ("have a change of heart", "reverse a decision"),
    ("hit the ground running", "start with immediate effectiveness"),
    ("hit the nail on the head", "describe exactly what's right"),
    ("in a nutshell", "in summary; briefly"),
    ("in hindsight", "looking back at the past"),
    ("in the long run", "over a long period of time"),
    ("in the same boat", "in the same difficult situation"),
    ("jump on the bandwagon", "join a popular trend"),
    ("keep a low profile", "avoid attention"),
    ("keep tabs on", "monitor closely"),
    ("kill two birds with one stone", "achieve two things at once"),
    ("learn the ropes", "learn how to do a job"),
    ("leave no stone unturned", "try every possible approach"),
    ("let the cat out of the bag", "reveal a secret"),
    ("level playing field", "fair and equal conditions"),
    ("make ends meet", "have enough money to live on"),
    ("miss the boat", "miss an opportunity"),
    ("move the goalposts", "change the rules unfairly"),
    ("no strings attached", "without conditions"),
    ("not rocket science", "not difficult to understand"),
    ("on the fence", "undecided"),
    ("on the same page", "in agreement"),
    ("once in a blue moon", "very rarely"),
    ("out of the blue", "unexpectedly"),
    ("play devil's advocate", "argue the opposite side"),
    ("play it by ear", "decide as you go"),
    ("pull strings", "use influence secretly"),
    ("pull the plug", "stop something; discontinue"),
    ("push the envelope", "go beyond the limits"),
    ("put all eggs in one basket", "risk everything on one plan"),
    ("rain check", "postpone to a later time"),
    ("read between the lines", "understand the hidden meaning"),
    ("ring a bell", "sound familiar"),
    ("rock the boat", "cause trouble or disruption"),
    ("run of the mill", "ordinary; nothing special"),
    ("see eye to eye", "agree completely"),
    ("sit on the fence", "avoid making a decision"),
    ("sleep on it", "think about before deciding"),
    ("speak volumes", "convey a lot without words"),
    ("stand the test of time", "remain valued over time"),
    ("state of the art", "the most modern and advanced"),
    ("steal the show", "attract the most attention"),
    ("take it with a grain of salt", "be skeptical about"),
    ("the ball is in your court", "it's your decision now"),
    ("the bottom line", "the most important point"),
    ("the elephant in the room", "an obvious problem being ignored"),
    ("the last straw", "the final problem that causes a reaction"),
    ("the tip of the iceberg", "a small visible part of a larger issue"),
    ("think outside the box", "think creatively"),
    ("throw in the towel", "give up"),
    ("turn a blind eye", "ignore deliberately"),
    ("turn over a new leaf", "make a fresh start"),
    ("under the weather", "feeling ill"),
    ("up in the air", "uncertain; not yet decided"),
    ("weigh the pros and cons", "consider advantages and disadvantages"),
    ("when push comes to shove", "when a situation becomes critical"),
    ("wrap your head around", "understand something complex"),
    # ── Extended: Business & Workplace ──
    ("a steep learning curve", "difficult initial period of acquiring new skills"),
    ("ahead of the curve", "more advanced than competitors"),
    ("behind the eight ball", "in a difficult or disadvantaged position"),
    ("bite the hand that feeds you", "harm someone who helps you"),
    ("bottom out", "reach the lowest point before recovery"),
    ("cut one's losses", "abandon a failing effort to prevent further loss"),
    ("dead in the water", "having no chance of success"),
    ("get down to brass tacks", "start dealing with essential facts"),
    ("get the short end of the stick", "receive unfair treatment"),
    ("get wind of", "hear about something secret"),
    ("go down the drain", "be wasted"),
    ("have a lot on one's plate", "be very busy with responsibilities"),
    ("have an axe to grind", "have a personal motive or grievance"),
    ("in over one's head", "involved in something too difficult"),
    ("jump the gun", "act prematurely"),
    ("keep one's cards close to one's chest", "not reveal one's plans"),
    ("let sleeping dogs lie", "avoid stirring up a settled situation"),
    ("nip it in the bud", "stop something at an early stage"),
    ("on thin ice", "in a risky or precarious situation"),
    ("pull one's weight", "do one's fair share of work"),
    ("raise the bar", "set a higher standard"),
    ("red tape", "excessive bureaucracy"),
    ("sail through", "accomplish very easily"),
    ("take the reins", "take control"),
    ("the big picture", "the overall situation"),
    ("the straw that broke the camel's back", "the final problem in a series"),
    ("throw a wrench in the works", "cause disruption to plans"),
    ("turn the tables", "reverse a disadvantage"),
    ("up to scratch", "meeting the required standard"),
    ("weather the storm", "survive a difficult period"),
    # ── Extended: Emotions & Mental State ──
    ("a weight off one's shoulders", "great relief from worry"),
    ("at one's wit's end", "completely frustrated; not knowing what to do"),
    ("come to terms with", "accept something difficult"),
    ("down in the dumps", "feeling depressed"),
    ("fly off the handle", "suddenly become very angry"),
    ("get a grip", "gain control of one's emotions"),
    ("have butterflies in one's stomach", "feel nervous"),
    ("keep a stiff upper lip", "remain calm and not show emotion"),
    ("keep one's cool", "stay calm under pressure"),
    ("lose one's temper", "become angry"),
    ("on cloud nine", "extremely happy"),
    ("on edge", "anxious; tense"),
    ("over the moon", "delighted; thrilled"),
    ("see red", "become very angry"),
    ("take a toll on", "have a damaging effect"),
    ("wear one's heart on one's sleeve", "openly show emotions"),
    # ── Extended: Relationships & Social ──
    ("a shoulder to cry on", "someone who listens sympathetically"),
    ("at each other's throats", "in fierce conflict"),
    ("be on the rocks", "be in difficulty (relationship)"),
    ("blood is thicker than water", "family ties are stronger than other bonds"),
    ("bury the hatchet", "make peace; end a disagreement"),
    ("get along like a house on fire", "become friends very quickly"),
    ("go back a long way", "have known each other for a long time"),
    ("have a soft spot for", "feel particular affection for"),
    ("keep someone at arm's length", "avoid becoming close"),
    ("rub someone the wrong way", "irritate or annoy someone"),
    ("take someone under one's wing", "mentor; look after someone"),
    ("the apple doesn't fall far from the tree", "children resemble their parents"),
    ("through thick and thin", "through good and bad times"),
    ("tied the knot", "got married"),
    # ── Extended: Health & Well-being ──
    ("a clean bill of health", "confirmation of good health"),
    ("alive and kicking", "in good health and active"),
    ("at death's door", "very seriously ill"),
    ("back on one's feet", "recovered from illness"),
    ("fit as a fiddle", "in excellent health"),
    ("go under the knife", "have surgery"),
    ("in the pink", "in very good health"),
    ("on the mend", "recovering from illness"),
    ("recharge one's batteries", "rest and regain energy"),
    ("run in the family", "be a common trait in a family"),
    ("take a turn for the worse", "suddenly become more ill"),
    # ── Extended: Parenting & Family Life ──
    ("a chip off the old block", "a child who resembles a parent"),
    ("cut the apron strings", "become independent from a parent"),
    ("empty nest syndrome", "sadness when children leave home"),
    ("have one's hands full", "be very busy (especially with children)"),
    ("like pulling teeth", "extremely difficult to get someone to do something"),
    ("run a tight ship", "manage strictly and efficiently"),
    ("set a good example", "behave in a way worth imitating"),
    ("the apple of one's eye", "a person one is very proud of and fond of"),
    ("wrap in cotton wool", "overprotect someone"),
    # ── Extended: Finance & Money ──
    ("a ballpark figure", "a rough estimate"),
    ("a penny for your thoughts", "asking what someone is thinking"),
    ("be in the black", "be profitable; not in debt"),
    ("be in the red", "be in debt"),
    ("bread and butter", "main source of income"),
    ("bring home the bacon", "earn money for the family"),
    ("feather one's nest", "enrich oneself (sometimes dishonestly)"),
    ("foot the bill", "pay for something"),
    ("go broke", "lose all one's money"),
    ("golden handshake", "large payment on leaving a job"),
    ("money doesn't grow on trees", "money is not easily obtained"),
    ("nest egg", "savings set aside for the future"),
    ("penny-wise, pound-foolish", "careful with small amounts, wasteful with large"),
    ("put one's money where one's mouth is", "back up words with action"),
    ("save for a rainy day", "save for an uncertain future time of need"),
    ("tighten one's belt", "spend less; economize"),
    # ── Extended: Everyday Conversation (CAE/CPE staples) ──
    ("a breath of fresh air", "a refreshing change"),
    ("a drop in the ocean", "a tiny, insignificant amount"),
    ("a hot potato", "a controversial or sensitive issue"),
    ("a piece of cake", "very easy"),
    ("actions speak louder than words", "what you do matters more than what you say"),
    ("all ears", "listening attentively"),
    ("at the drop of a hat", "immediately; without hesitation"),
    ("beat a dead horse", "continue arguing a settled matter"),
    ("better late than never", "doing something late is better than not at all"),
    ("burn the candle at both ends", "overwork; exhaust oneself"),
    ("by the skin of one's teeth", "barely; by a very narrow margin"),
    ("cold turkey", "abruptly stopping an addiction"),
    ("cry over spilled milk", "regret something that cannot be undone"),
    ("cut someone some slack", "be less critical; allow some leeway"),
    ("every cloud has a silver lining", "bad situations have some positive aspect"),
    ("get one's act together", "start behaving responsibly"),
    ("give it a shot", "try something"),
    ("go overboard", "do something to excess"),
    ("have second thoughts", "begin to doubt a decision"),
    ("hit a snag", "encounter an unexpected problem"),
    ("hit rock bottom", "reach the lowest possible point"),
    ("in one's element", "in a comfortable, natural environment"),
    ("it takes two to tango", "both parties are responsible"),
    ("jump through hoops", "go through a complex process"),
    ("keep one's eye on the ball", "stay focused on what matters"),
    ("make a mountain out of a molehill", "exaggerate a small problem"),
    ("miss the mark", "fail to achieve the intended result"),
    ("off the top of one's head", "without careful thought; from memory"),
    ("on the tip of one's tongue", "almost able to remember"),
    ("put one's foot down", "insist firmly"),
    ("put one's foot in one's mouth", "say something embarrassing or tactless"),
    ("sit tight", "wait patiently"),
    ("spill the beans", "reveal a secret"),
    ("take the bull by the horns", "deal with a problem decisively"),
    ("the whole nine yards", "everything; all of it"),
    ("time flies", "time passes quickly"),
    ("turn the corner", "begin to recover or improve"),
    ("two sides of the same coin", "two aspects of the same thing"),
    ("walking on eggshells", "being very careful not to upset someone"),
    ("you can't judge a book by its cover", "don't judge by appearance"),
]


# ── REAL-LIFE CATEGORIES ──────────────────────────────────────────

# ── Parenting & Childcare ─────────────────────────────────────────
PARENTING: List[Tuple[str, str]] = [
    ("playdate", "arranged meeting for children to play together"),
    ("tantrum", "uncontrolled outburst of anger/frustration (child)"),
    ("time-out", "punishment where child sits alone briefly"),
    ("potty-trained", "child who has learned to use the toilet"),
    ("picky eater", "person who refuses many foods"),
    ("bedtime routine", "regular sequence of activities before sleep"),
    ("sleep training", "teaching a baby to fall asleep independently"),
    ("teething", "process of baby's teeth emerging"),
    ("crawl", "move on hands and knees (baby stage)"),
    ("toddle", "walk unsteadily like a small child"),
    ("baby-proof", "make a space safe for a baby"),
    ("nap", "short daytime sleep"),
    ("lullaby", "gentle song to help a child sleep"),
    ("pacifier", "rubber/silicone device baby sucks on for comfort"),
    ("stroller", "wheeled chair for pushing a baby/toddler"),
    ("car seat", "safety seat for children in vehicles"),
    ("diaper", "absorbent garment worn by babies"),
    ("formula", "manufactured baby milk substitute"),
    ("breastfeed", "feed a baby with mother's milk"),
    ("wean", "gradually stop breastfeeding; introduce solid food"),
    ("milestone", "important developmental achievement"),
    ("screen time", "time spent using electronic devices"),
    ("act up", "behave badly (children)"),
    ("ground", "punish by restricting activities/going out"),
    ("curfew", "time by which a person must be home"),
    ("allowance", "regular money given to a child"),
    ("playpen", "enclosed area for a baby to play safely"),
    ("babysitter", "person paid to look after children temporarily"),
    ("daycare", "place where young children are cared for during the day"),
    ("preschool", "school for children before kindergarten (ages 3-5)"),
    ("kindergarten", "school for children aged 5-6"),
    ("recess", "break during school for play"),
    ("bully", "person who intimidates or harasses others"),
    ("sibling rivalry", "competition or jealousy between brothers/sisters"),
    ("spoil", "overindulge a child; harm by excessive kindness"),
    ("discipline", "training to follow rules; punishment"),
    ("nurture", "care for and encourage growth/development"),
    ("helicopter parent", "overprotective parent who hovers over child"),
    ("attachment", "emotional bond between parent and child"),
    ("separation anxiety", "distress when separated from caregiver"),
    ("fussy", "hard to please; crying easily (baby)"),
    ("colicky", "having episodes of excessive crying (infant)"),
    ("growth spurt", "period of rapid physical growth"),
    ("terrible twos", "phase of defiant behavior around age 2"),
    ("potty", "small toilet for children"),
]

# ── Household & Home Life ─────────────────────────────────────────
HOUSEHOLD: List[Tuple[str, str]] = [
    ("do the laundry", "wash clothes"),
    ("fold the laundry", "neatly arrange clean clothes"),
    ("take out the trash", "bring garbage outside for collection"),
    ("sort the recycling", "separate recyclable materials"),
    ("vacuum", "clean with a vacuum cleaner"),
    ("mop the floor", "clean floor with wet mop"),
    ("dust", "remove dust from surfaces"),
    ("scrub", "clean by rubbing hard"),
    ("declutter", "remove unnecessary items; tidy up"),
    ("unclog", "remove a blockage from a pipe/drain"),
    ("leaky", "having a leak; dripping"),
    ("faucet", "tap; device controlling water flow"),
    ("plumber", "person who fixes water pipes/plumbing"),
    ("electrician", "person who works on electrical systems"),
    ("handyman", "person skilled at home repairs"),
    ("DIY", "do-it-yourself; home improvement without professionals"),
    ("power outage", "electricity failure"),
    ("blackout", "total loss of electrical power"),
    ("appliance", "household machine (fridge, washer, etc.)"),
    ("renovate", "restore or improve a building"),
    ("remodel", "change the structure or design of a room/house"),
    ("mortgage", "loan for buying property"),
    ("landlord", "person who rents out property"),
    ("tenant", "person who rents and lives in property"),
    ("lease", "contract for renting property"),
    ("utilities", "essential services: electricity, water, gas"),
    ("property tax", "tax paid on owned real estate"),
    ("homeowner", "person who owns their home"),
    ("HOA", "homeowner's association; manages shared property"),
    ("curb appeal", "attractiveness of a property from the street"),
    ("move in", "begin living in a new place"),
    ("move out", "leave a place of residence"),
    ("settle in", "become comfortable in a new home"),
    ("housewarming", "party celebrating moving into a new home"),
    ("spring cleaning", "thorough annual cleaning of a house"),
    ("pest control", "managing insects/rodents in a home"),
    ("childproof", "make safe for children"),
    ("smoke detector", "device that alerts to fire/smoke"),
    ("thermostat", "device controlling heating/cooling temperature"),
    ("insulation", "material preventing heat loss"),
    ("pantry", "storage room/cabinet for food"),
    ("countertop", "flat work surface in kitchen"),
    ("backsplash", "protective area behind a kitchen counter"),
    ("garbage disposal", "device in sink that grinds food waste"),
    ("load the dishwasher", "put dishes into the dishwashing machine"),
]

# ── Social & Informal ─────────────────────────────────────────────
SOCIAL: List[Tuple[str, str]] = [
    ("get-together", "informal social gathering"),
    ("catch up", "exchange news after time apart"),
    ("hang out", "spend time casually with someone"),
    ("rain check", "postpone an invitation to another time"),
    ("no-show", "person who fails to appear as expected"),
    ("flaky", "unreliable; frequently cancels plans"),
    ("laid-back", "relaxed and easy-going"),
    ("hit it off", "immediately get along well with someone"),
    ("break the ice", "relieve tension at a first meeting"),
    ("small talk", "polite conversation about unimportant things"),
    ("ghosting", "suddenly cutting off all communication"),
    ("stood up", "failed to show for a date/meeting"),
    ("RSVP", "respond to an invitation"),
    ("potluck", "meal where each guest brings a dish"),
    ("BYOB", "bring your own bottle/beverage (to a party)"),
    ("host", "person giving a party; to organize an event"),
    ("mingle", "move around talking to different people at a party"),
    ("plus-one", "guest someone brings to an event"),
    ("networking", "making professional/social connections"),
    ("acquaintance", "person you know slightly but not well"),
    ("clique", "exclusive group of people"),
    ("outgoing", "friendly and socially confident"),
    ("introverted", "preferring solitude; quiet in social settings"),
    ("awkward", "uncomfortable; lacking social ease"),
    ("cringe", "feel embarrassment or discomfort"),
    ("gossip", "casual talk about other people's affairs"),
    ("vent", "express strong emotions/frustrations"),
    ("chit-chat", "light, informal conversation"),
    ("bond", "form a close relationship"),
    ("drift apart", "gradually lose closeness with someone"),
    ("make amends", "do something to correct a wrongdoing"),
    ("hold a grudge", "maintain resentment over time"),
    ("give the cold shoulder", "deliberately ignore someone"),
    ("two-faced", "deceitful; acting differently behind someone's back"),
    ("people person", "someone who enjoys and is good with people"),
    ("wallflower", "shy person who avoids social interaction"),
    ("the life of the party", "the most entertaining person at an event"),
    ("party pooper", "person who ruins others' fun"),
    ("FOMO", "fear of missing out"),
    ("go-to person", "the reliable person you turn to for help"),
]

# ── Workplace Casual ──────────────────────────────────────────────
WORKPLACE: List[Tuple[str, str]] = [
    ("touch base", "make brief contact to exchange updates"),
    ("circle back", "return to a topic or discussion later"),
    ("heads-up", "advance warning or notification"),
    ("on the same page", "in agreement; having shared understanding"),
    ("no-brainer", "decision that requires no thought; obvious choice"),
    ("crunch time", "period of intense pressure before a deadline"),
    ("bandwidth", "capacity to handle work (figurative)"),
    ("deliverable", "tangible output or result of work"),
    ("stakeholder", "person with interest in a project/decision"),
    ("bottleneck", "point of congestion slowing a process"),
    ("streamline", "make a process more efficient"),
    ("synergy", "combined effect greater than individual parts"),
    ("pivot", "change direction or strategy"),
    ("scalable", "able to grow or expand efficiently"),
    ("onboard", "integrate a new employee into a company"),
    ("offboard", "manage an employee's departure process"),
    ("micromanage", "control every small detail of others' work"),
    ("delegate", "assign tasks to subordinates"),
    ("burnout", "exhaustion from chronic workplace stress"),
    ("work-life balance", "equilibrium between job and personal life"),
    ("remote work", "working from outside the office"),
    ("hybrid", "combining office and remote work"),
    ("stand-up", "brief daily team meeting (often standing)"),
    ("retrospective", "meeting reviewing what went well/badly"),
    ("action item", "specific task assigned during a meeting"),
    ("follow up", "check on progress after initial contact"),
    ("escalate", "raise an issue to higher authority"),
    ("pushback", "resistance or objection to a proposal"),
    ("buy-in", "agreement and support from stakeholders"),
    ("low-hanging fruit", "easy tasks/wins requiring minimal effort"),
    ("move the needle", "make a noticeable difference"),
    ("deep dive", "thorough analysis of a topic"),
    ("pain point", "persistent problem causing frustration"),
    ("workaround", "temporary solution to a problem"),
    ("scope creep", "uncontrolled expansion of project requirements"),
    ("deadline", "final date by which something must be completed"),
    ("ballpark", "rough estimate or approximation"),
    ("KPI", "key performance indicator; metric for success"),
    ("OKR", "objectives and key results; goal-setting framework"),
    ("sync", "synchronize; align on information"),
    ("loop in", "include someone in communication/discussion"),
    ("sign off", "give formal approval"),
    ("table", "postpone discussion of a topic (US) / propose for discussion (UK)"),
    ("take offline", "discuss privately outside the current meeting"),
    ("boilerplate", "standard text/template reused without changes"),
]

# ── Health & Medical (everyday) ───────────────────────────────────
HEALTH: List[Tuple[str, str]] = [
    ("copay", "fixed amount patient pays for medical service"),
    ("deductible", "amount paid before insurance covers costs"),
    ("premium", "regular payment for insurance coverage"),
    ("over-the-counter", "medicine available without prescription"),
    ("prescription", "doctor's written order for medicine"),
    ("side effects", "unintended effects of medication"),
    ("allergic reaction", "immune system response to a substance"),
    ("refill", "get another supply of a prescription"),
    ("dosage", "amount of medicine to take"),
    ("chronic", "long-lasting; persistent (condition)"),
    ("acute", "severe and sudden (condition)"),
    ("contagious", "able to spread from person to person"),
    ("symptoms", "physical signs of illness"),
    ("diagnosis", "identification of an illness or condition"),
    ("prognosis", "expected course and outcome of a condition"),
    ("follow-up appointment", "subsequent visit to check progress"),
    ("physical", "routine medical examination"),
    ("checkup", "regular health examination"),
    ("blood work", "laboratory tests on blood samples"),
    ("screening", "testing for diseases before symptoms appear"),
    ("vaccination", "injection to prevent disease"),
    ("booster", "additional dose to maintain immunity"),
    ("immune system", "body's defense against infection"),
    ("inflammation", "body's response to injury/infection; swelling"),
    ("sprain", "stretch or tear a ligament"),
    ("fracture", "break in a bone"),
    ("stitches", "sutures closing a wound"),
    ("concussion", "brain injury from a blow to the head"),
    ("nausea", "feeling of sickness in the stomach"),
    ("fatigue", "extreme tiredness"),
    ("insomnia", "inability to sleep"),
    ("anxiety", "excessive worry or nervousness"),
    ("depression", "persistent sadness and loss of interest"),
    ("therapy", "treatment for mental/physical health"),
    ("therapist", "professional who provides therapy"),
    ("referral", "direction to a specialist by a doctor"),
    ("specialist", "doctor focused on a specific area"),
    ("pediatrician", "doctor specializing in children"),
    ("urgent care", "medical facility for non-emergency issues"),
    ("ER", "emergency room; hospital emergency department"),
    ("rehab", "rehabilitation; recovery program"),
    ("holistic", "treating the whole person, not just symptoms"),
    ("wellness", "state of being in good health"),
    ("sedentary", "involving much sitting; physically inactive"),
    ("dietary", "relating to food and nutrition"),
]

# ── Emotions & Mental States (nuanced C1+) ────────────────────────
EMOTIONS: List[Tuple[str, str]] = [
    ("overwhelmed", "feeling too much to handle"),
    ("fed up", "annoyed or bored beyond patience"),
    ("burned out", "exhausted from overwork/stress"),
    ("resentful", "feeling bitter about unfair treatment"),
    ("gutted", "extremely disappointed (British informal)"),
    ("stoked", "very excited and enthusiastic"),
    ("bummed", "disappointed or saddened"),
    ("relieved", "feeling worry has been removed"),
    ("apprehensive", "anxious about something upcoming"),
    ("ambivalent", "having mixed or conflicting feelings"),
    ("nostalgic", "longing for the past"),
    ("empathetic", "able to understand others' feelings"),
    ("compassionate", "feeling concern and desire to help"),
    ("indifferent", "having no particular interest or sympathy"),
    ("apathetic", "lacking interest or enthusiasm"),
    ("exasperated", "intensely irritated and frustrated"),
    ("mortified", "extremely embarrassed"),
    ("humiliated", "made to feel ashamed or foolish publicly"),
    ("vindicated", "proven right after being doubted"),
    ("validated", "feeling one's views are recognized as correct"),
    ("taken aback", "surprised or shocked"),
    ("dumbfounded", "extremely surprised; speechless"),
    ("baffled", "completely unable to understand"),
    ("perplexed", "puzzled and confused"),
    ("wistful", "having a feeling of vague sadness or longing"),
    ("melancholy", "deep, persistent sadness"),
    ("elated", "extremely happy and excited"),
    ("euphoric", "feeling intense happiness or excitement"),
    ("content", "peacefully happy; satisfied"),
    ("complacent", "smugly self-satisfied; uncritical"),
    ("disillusioned", "disappointed by discovering reality differs from expectations"),
    ("jaded", "tired and lacking enthusiasm from too much experience"),
    ("cynical", "distrusting others' motives; pessimistic"),
    ("bitter", "angry and resentful about past unfairness"),
    ("remorseful", "feeling deep regret for wrongdoing"),
    ("grateful", "feeling or showing thanks"),
    ("indebted", "owing gratitude; feeling obligated"),
    ("vulnerable", "emotionally exposed; open to harm"),
    ("insecure", "lacking confidence; uncertain of oneself"),
    ("self-conscious", "excessively aware of oneself; embarrassed"),
    ("composed", "calm and in control of emotions"),
    ("resilient", "able to recover quickly from difficulties"),
    ("thick-skinned", "not easily offended or upset"),
    ("thin-skinned", "easily offended or hurt"),
    ("triggered", "having a strong emotional reaction to something"),
]

# ── Cultural & Social Life ────────────────────────────────────────
CULTURAL: List[Tuple[str, str]] = [
    ("potluck", "meal where each guest brings a dish to share"),
    ("garage sale", "sale of used items from someone's home"),
    ("yard sale", "same as garage sale; held in the yard"),
    ("thrift store", "shop selling secondhand goods cheaply"),
    ("Thanksgiving", "US holiday for giving thanks (4th Thursday Nov)"),
    ("trick-or-treat", "Halloween tradition: children ask for candy"),
    ("baby shower", "party celebrating an expected baby with gifts"),
    ("bridal shower", "party for a bride-to-be before the wedding"),
    ("bachelor party", "celebration before a man's wedding"),
    ("bachelorette party", "celebration before a woman's wedding"),
    ("rehearsal dinner", "dinner before a wedding for the wedding party"),
    ("graduation ceremony", "formal event marking completion of studies"),
    ("homecoming", "annual celebration welcoming back alumni"),
    ("prom", "formal dance event at a high school"),
    ("tailgate", "socialize in parking lot before a sports event"),
    ("Super Bowl", "annual US football championship; major cultural event"),
    ("Black Friday", "major shopping day after US Thanksgiving"),
    ("Cyber Monday", "online shopping day after Black Friday"),
    ("road trip", "long journey by car, often for pleasure"),
    ("staycation", "vacation spent at home or nearby"),
    ("bucket list", "list of things to do before dying"),
    ("comfort food", "food providing nostalgic or emotional comfort"),
    ("foodie", "person with keen interest in food and cuisine"),
    ("brunch", "late morning meal combining breakfast and lunch"),
    ("happy hour", "time when drinks are sold at reduced prices"),
    ("designated driver", "person who stays sober to drive others"),
    ("tip", "gratuity; extra money for service (15-20% in US)"),
    ("split the bill", "divide the cost equally among diners"),
    ("doggy bag", "container for taking leftover restaurant food home"),
    ("takeout", "food bought at a restaurant to eat elsewhere"),
    ("drive-through", "service window where you order from your car"),
    ("HOA", "homeowner's association managing shared community rules"),
    ("PTA", "parent-teacher association at a school"),
    ("volunteer", "person who works without pay for a cause"),
    ("nonprofit", "organization not operating for profit"),
    ("fundraiser", "event or campaign to collect money for a cause"),
    ("community service", "unpaid work benefiting the community"),
    ("block party", "outdoor party for a neighborhood"),
    ("neighborhood watch", "residents monitoring for suspicious activity"),
    ("carpool", "sharing car rides with others to save cost/pollution"),
]

# ── Relationships & Communication ─────────────────────────────────
RELATIONSHIPS: List[Tuple[str, str]] = [
    ("significant other", "romantic partner (gender-neutral term)"),
    ("partner", "life companion; business associate"),
    ("fiancé", "man engaged to be married"),
    ("fiancée", "woman engaged to be married"),
    ("spouse", "husband or wife"),
    ("ex", "former partner or spouse"),
    ("blended family", "family with children from previous relationships"),
    ("custody", "legal right to care for a child after divorce"),
    ("co-parent", "share parenting duties (often after separation)"),
    ("boundaries", "personal limits in relationships"),
    ("toxic", "harmful to wellbeing (relationship/person)"),
    ("codependent", "excessively reliant on another person emotionally"),
    ("gaslighting", "manipulating someone into questioning their reality"),
    ("love language", "way a person prefers to give/receive affection"),
    ("quality time", "focused, undivided attention given to someone"),
    ("compromise", "settle a dispute by each side giving up something"),
    ("give and take", "mutual concession in a relationship"),
    ("communicate", "share thoughts and feelings effectively"),
    ("open up", "become willing to talk about personal feelings"),
    ("bottle up", "suppress emotions; not express feelings"),
    ("lash out", "attack verbally in anger"),
    ("clear the air", "resolve tension through honest discussion"),
    ("heart-to-heart", "intimate, honest conversation"),
    ("tough love", "strict approach motivated by genuine care"),
    ("unconditional", "without conditions or limitations"),
    ("supportive", "providing encouragement and help"),
    ("emotionally available", "willing and able to connect emotionally"),
    ("commitment", "dedication to a relationship or cause"),
    ("infidelity", "unfaithfulness in a relationship"),
    ("trust issues", "difficulty trusting others due to past experience"),
    ("rebound", "relationship entered shortly after a breakup"),
    ("settle down", "begin living a stable, domestic life"),
    ("grow apart", "gradually become less close over time"),
    ("make up", "reconcile after a quarrel"),
    ("break up", "end a romantic relationship"),
    ("get back together", "resume a relationship after breaking up"),
    ("move on", "accept a loss and continue with life"),
    ("closure", "sense of resolution after an ending"),
    ("let go", "release attachment to something/someone"),
    ("take for granted", "fail to appreciate someone's value"),
]

# ── Finance & Adult Life ──────────────────────────────────────────
FINANCE: List[Tuple[str, str]] = [
    ("budget", "plan for spending money"),
    ("savings", "money set aside for future use"),
    ("retirement", "leaving work permanently; life after career"),
    ("401k", "US employer-sponsored retirement savings plan"),
    ("pension", "regular payment after retirement"),
    ("investment", "putting money into something expecting returns"),
    ("stock", "share of ownership in a company"),
    ("portfolio", "collection of investments"),
    ("diversify", "spread investments to reduce risk"),
    ("compound interest", "interest earned on interest"),
    ("debt", "money owed"),
    ("credit score", "numerical rating of creditworthiness"),
    ("credit card", "card for borrowing money for purchases"),
    ("interest rate", "percentage charged for borrowing money"),
    ("APR", "annual percentage rate; yearly cost of borrowing"),
    ("down payment", "initial partial payment on a large purchase"),
    ("installment", "one of a series of regular payments"),
    ("refinance", "replace a loan with a new one at better terms"),
    ("equity", "ownership value; property value minus debt"),
    ("tax return", "annual filing of income and tax information"),
    ("tax bracket", "income range that determines tax rate"),
    ("withholding", "tax deducted from wages before payment"),
    ("gross income", "total income before deductions"),
    ("net income", "income after taxes and deductions"),
    ("paycheck", "regular payment from employer"),
    ("direct deposit", "automatic transfer of pay to bank account"),
    ("overdraft", "withdrawing more money than in an account"),
    ("wire transfer", "electronic transfer of money between banks"),
    ("inflation", "general increase in prices over time"),
    ("cost of living", "amount needed for basic expenses in an area"),
    ("frugal", "careful with money; avoiding waste"),
    ("splurge", "spend money freely or extravagantly"),
    ("impulse buy", "unplanned purchase driven by sudden desire"),
    ("window shopping", "looking at goods without intending to buy"),
    ("bargain", "something bought cheaply; a good deal"),
    ("rip-off", "something unfairly expensive; a fraud"),
    ("broke", "having no money (informal)"),
    ("well-off", "wealthy; financially comfortable"),
    ("affluent", "having a lot of money; wealthy (formal)"),
    ("live paycheck to paycheck", "spend all earnings with no savings"),
]


def get_all_lists() -> dict:
    """Return all word lists as {category: [(word, hint), ...]}."""
    return {
        "awl": AWL,
        "phrasal": PHRASAL_VERBS,
        "idiom": IDIOMS,
        "parenting": PARENTING,
        "household": HOUSEHOLD,
        "social": SOCIAL,
        "workplace": WORKPLACE,
        "health": HEALTH,
        "emotions": EMOTIONS,
        "cultural": CULTURAL,
        "relationships": RELATIONSHIPS,
        "finance": FINANCE,
    }


def get_list(category: str) -> List[Tuple[str, str]]:
    """Get a specific word list by category."""
    lists = get_all_lists()
    if category not in lists:
        raise ValueError(f"Unknown category: {category!r}. Use: {list(lists.keys())}")
    return lists[category]


def get_stats() -> dict:
    """Return word counts by category."""
    return {cat: len(words) for cat, words in get_all_lists().items()}
